name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        qt_ver: [5.15.2, 5.14.2, 5.13.2]

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt_ver }}
        modules: 'qtwebengine'
    - uses: actions/checkout@v2
    - name: make
      run: |
        qmake CONFIG+=cross_compile
        make
